name: CMake

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        config: [Debug, Release]
        shared: [dynamic, static]

    env:
      VCPKG_ROOT: ${{github.workspace}}/vcpkg
      VCPKG_LIBRARY_LINKAGE: ${{matrix.shared}}

    steps:
    - uses: actions/checkout@v2
    # Install latest CMake.
    - uses: lukka/get-cmake@latest
    - name: Checkout microsoft/vcpkg
      uses: actions/checkout@v2
      with:
        repository: microsoft/vcpkg
        path: vcpkg
    - name: Bootstrap Vcpkg
      working-directory: ${{env.VCPKG_ROOT}}
      run: |
        ./bootstrap-vcpkg.sh
    - name: Vcpkg install dependences
      run: |
        $VCPKG_ROOT/vcpkg install sdl2 zlib
    - name: CMake configure
      run: |
        cmake -S . -B build \
          -DCMAKE_INSTALL_PREFIX=local \
          -DBUILD_SHARED_LIBS=${{ matrix.shared == 'dynamic' && 'TRUE' || 'FALSE' }} \
          -DLIBTCOD_SAMPLES=ON \
          -DLIBTCOD_TESTS=ON \
          -Wdev \
          --warn-uninitialized
    - name: CMake build
      run: |
        cmake --build build --config ${{matrix.config}}
    - name: List build files
      run: find build/
    - name: Run tests
      env:
        LD_LIBRARY_PATH: build/lib
      run: |
        build/bin/unittest ~[!nonportable]
    - name: CMake test install
      run: |
        cmake --install build --config ${{matrix.config}}
